GOTHAM_ROSTER = [
    {"name": "Ann-Katrin Berger", "number": 1, "age": 32, "country": "Germany", "position": "Goalkeeper"},
    {"name": "Ryan Campbell", "number": 18, "age": 26, "country": "USA", "position": "Goalkeeper"},
    {"name": "Shelby Hogan", "number": 30, "age": 25, "country": "USA", "position": "Goalkeeper"},
    {"name": "Teagan Wy", "number": 13, "age": 22, "country": "USA", "position": "Goalkeeper"},
    {"name": "Bruninha", "number": 3, "age": 26, "country": "Brazil", "position": "Defender"},
    {"name": "Jess Carter", "number": 7, "age": 28, "country": "England", "position": "Defender"},
    {"name": "Tierna Davidson", "number": 14, "age": 26, "country": "USA", "position": "Defender"},
    {"name": "Kayla Duran", "number": 4, "age": 22, "country": "USA", "position": "Defender"},
    {"name": "Mandy Freeman", "number": 5, "age": 27, "country": "USA", "position": "Defender"},
    {"name": "Lilly Reale", "number": 2, "age": 24, "country": "USA", "position": "Defender"},
    {"name": "Emily Sonnett", "number": 16, "age": 30, "country": "USA", "position": "Defender"},
    {"name": "Rose Lavelle", "number": 16, "age": 29, "country": "USA", "position": "Midfielder"},
    {"name": "Savannah McCaskill", "number": 8, "age": 28, "country": "USA", "position": "Midfielder"},
    {"name": "Jaedyn Shaw", "number": 17, "age": 21, "country": "USA", "position": "Midfielder"},
    {"name": "Taryn Torres", "number": 6, "age": 29, "country": "USA", "position": "Midfielder"},
    {"name": "Talia Sommer", "number": 19, "age": 24, "country": "Israel", "position": "Midfielder"},
    {"name": "Midge Purce", "number": 9, "age": 29, "country": "USA", "position": "Forward"},
    {"name": "Katie Stengel", "number": 20, "age": 31, "country": "USA", "position": "Forward"},
    {"name": "Mak Whitham", "number": 11, "age": 23, "country": "USA", "position": "Forward"},
]

DENVER_ROSTER = [
    {"name": "Abby Smith", "number": 1, "age": 32, "country": "USA", "position": "Goalkeeper"},
    {"name": "Jordan Nytes", "number": 17, "age": 21, "country": "USA", "position": "Goalkeeper"},
    {"name": "Pauline Peyraud-Magnin", "number": 21, "age": 34, "country": "France", "position": "Goalkeeper"},
    {"name": "Megan Reid", "number": 2, "age": 29, "country": "Canada", "position": "Defender"},
    {"name": "Kaleigh Kurtz", "number": 3, "age": 31, "country": "USA", "position": "Defender"},
    {"name": "Natalie Means", "number": 4, "age": 22, "country": "USA", "position": "Defender"},
    {"name": "Ayo Oke", "number": 7, "age": 22, "country": "USA", "position": "Defender"},
    {"name": "Carson Pickett", "number": 16, "age": 32, "country": "USA", "position": "Defender"},
    {"name": "Eva Gaetino", "number": 23, "age": 23, "country": "USA", "position": "Defender"},
    {"name": "Camryn Biegalski", "number": 30, "age": 27, "country": "USA", "position": "Defender"},
    {"name": "Devin Lynch", "number": 5, "age": 22, "country": "USA", "position": "Midfielder"},
    {"name": "Emma Regan", "number": 8, "age": 26, "country": "Canada", "position": "Midfielder"},
    {"name": "Yuna McCormack", "number": 14, "age": 21, "country": "USA", "position": "Midfielder"},
    {"name": "Jordan Baggett", "number": 15, "age": 29, "country": "USA", "position": "Midfielder"},
    {"name": "Lourdes Bosch", "number": 19, "age": 24, "country": "Mexico", "position": "Midfielder"},
    {"name": "Delanie Sheehan", "number": 24, "age": 27, "country": "USA", "position": "Midfielder"},
    {"name": "Meg Boade", "number": 34, "age": 23, "country": "USA", "position": "Midfielder"},
    {"name": "Lindsey Heaps", "number": 10, "age": 31, "country": "USA", "position": "Midfielder", "note": "USWNT Captain"},
    {"name": "Yazmeen Ryan", "number": 9, "age": 27, "country": "USA", "position": "Forward"},
    {"name": "Ally Brazier", "number": 11, "age": 29, "country": "USA", "position": "Forward"},
    {"name": "Jasmine Aikey", "number": 12, "age": 20, "country": "USA", "position": "Forward"},
    {"name": "Janine Sonis", "number": 6, "age": 31, "country": "Canada", "position": "Forward"},
    {"name": "Melissa Kössler", "number": 25, "age": 26, "country": "Germany", "position": "Forward", "note": "Top scorer 3 goals"},
    {"name": "Natasha Flint", "number": 26, "age": 29, "country": "England", "position": "Forward", "note": "On loan"},
    {"name": "Olivia Thomas", "number": 33, "age": 20, "country": "USA", "position": "Forward"},
    {"name": "Nahikari García", "number": 79, "age": 29, "country": "Spain", "position": "Forward"},
    {"name": "Yuzuki Yamamoto", "number": None, "age": None, "country": "Japan", "position": "Forward"},
]

TEAMS = {
    "gotham-fc": GOTHAM_ROSTER,
    "denver-summit": DENVER_ROSTER,
}
